name: Docker release

on:
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+

env:
    REGISTRY: registry.hub.docker.com
    IMAGE_NAME: delibird

jobs:
    image:
        name: Build and push Docker image
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 19
            - run: pnpm install
            - name: Build app
              run: pnpm build

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                  username: arayaryoma
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: metadata
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
